version: 0.2.0-{build}

environment:
  matrix:
    - platform: x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
branches:
  only:
    - master

image: Visual Studio 2015

init:

install:
  - ps: Install-Product node 7 x64
  - set CI=true
  - npm i -g electron

build: off

shallow_clone: true

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm test

on_success:
- npm run pack
